import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import assert from "node:assert/strict";
import { test } from "node:test";
import type { StepConfig } from "../scripts/generateSteps.ts";
import { buildWalkResultSchema, buildWorkflowScript, generateWorkflow, getFirstBox } from "../scripts/generateWorkflow.ts";
import { getSchemaFromTemplate } from "../scripts/templateSchema.ts";

// Builds a throwaway project holding one steps.json and the template files it points at.
function buildProject(blocks: { box: string; output: Record<string, unknown> }[]) {
    const projectRoot = mkdtempSync(join(tmpdir(), "generate-workflow-"));
    mkdirSync(join(projectRoot, "steps"));
    const entries = blocks.map(block => {
        const template = { input: {}, output: block.output };
        writeFileSync(join(projectRoot, "steps", `${block.box}.template.json`), JSON.stringify(template));
        return { box: block.box, script: `steps/${block.box}.ts`, template: `steps/${block.box}.template.json`, next: [] };
    });
    const config: StepConfig = { "one.mmd": entries };
    const configFile = join(projectRoot, "steps.json");
    writeFileSync(configFile, JSON.stringify(config));
    return { projectRoot, config, configFile };
}

test("test_buildWalkResultSchema_closesTheEnvelopeTheHookReturns", () => {
    const { config, projectRoot } = buildProject([{ box: "A", output: { box: "A", signal: "continue" } }]);
    const schema = buildWalkResultSchema(config, projectRoot) as Record<string, unknown>;
    assert.deepEqual(schema.required, ["ok", "ran", "stoppedAt", "why", "output"]);
    assert.equal(schema.additionalProperties, false);
});

test("test_buildWalkResultSchema_offersOneOutputShapePerBlock", () => {
    const { config, projectRoot } = buildProject([
        { box: "A", output: { box: "A", signal: "continue", files: 0 } },
        { box: "B", output: { box: "B", signal: "stop" } },
    ]);
    const schema = buildWalkResultSchema(config, projectRoot) as Record<string, Record<string, Record<string, unknown[]>>>;
    assert.equal(schema.properties!.output!.anyOf!.length, 2);
});

// The point of the whole task: the schema is the template, not a hand-written copy of it.
test("test_buildWalkResultSchema_buildsEachOutputShapeFromThatBlocksTemplate", () => {
    const output = { box: "A", signal: "continue", files: 0 };
    const { config, projectRoot } = buildProject([{ box: "A", output }]);
    const schema = buildWalkResultSchema(config, projectRoot) as Record<string, Record<string, Record<string, unknown[]>>>;
    assert.deepEqual(schema.properties!.output!.anyOf![0], getSchemaFromTemplate(output));
});

test("test_getFirstBox_namesTheFirstBoxOfTheFirstDiagram", () => {
    const { config } = buildProject([{ box: "A", output: { box: "A" } }, { box: "B", output: { box: "B" } }]);
    assert.equal(getFirstBox(config), "A");
});

test("test_buildWorkflowScript_startsWithAMetaBlockAndSaysNotToEditIt", () => {
    const { config, projectRoot } = buildProject([{ box: "A", output: { box: "A", signal: "stop" } }]);
    const script = buildWorkflowScript(config, projectRoot);
    assert.match(script, /Do not edit this file/);
    assert.match(script, /export const meta = \{\n {4}name: 'run-step',/);
});

test("test_buildWorkflowScript_asksOneAgentToTypeTheCommandWithTheSchema", () => {
    const { config, projectRoot } = buildProject([{ box: "A", output: { box: "A", signal: "stop" } }]);
    const script = buildWorkflowScript(config, projectRoot);
    assert.match(script, /\/run-step \$\{startBox\} \$\{startInput\}/);
    assert.match(script, /schema: WALK_RESULT_SCHEMA/);
});

test("test_buildWorkflowScript_defaultsTheStartBoxToTheFirstBoxInTheConfig", () => {
    const { config, projectRoot } = buildProject([{ box: "FIRST", output: { box: "FIRST", signal: "stop" } }]);
    assert.match(buildWorkflowScript(config, projectRoot), /args\?\.box \?\? "FIRST"/);
});

test("test_generateWorkflow_writesTheScriptToTheGivenPath", () => {
    const { configFile, projectRoot } = buildProject([{ box: "A", output: { box: "A", signal: "stop" } }]);
    const workflowFile = join(projectRoot, ".claude/workflows/run-step.workflow.js");
    generateWorkflow(configFile, workflowFile, projectRoot);
    assert.match(readFileSync(workflowFile, "utf8"), /export const meta/);
});
