Object.assign(GRAPH.skills, {

  'tackle-tasks': {
    title: 'tackle-tasks',
    file: 'skills/tackle-tasks/SKILL.md',
    blurb: 'The orchestrator. Three scripts prepare the work, one Workflow call executes it, the model handles the human parts at both ends.',
    steps: [
      { id: 'tt1', label: 'inject blocked status', lines: '8', kind: 'det', cost: 'fast',
        excerpt: '- blocked status: !`node .../checkBlockers.ts` \'$ARGUMENTS\'',
        why: 'Pure JSON read.' },
      { id: 'tt2', label: 'inject unblocked task details', lines: '9', kind: 'det', cost: 'fast',
        excerpt: 'u=$(node .../checkBlockers.ts --unblocked \'$ARGUMENTS\'); [ -n "$u" ] && node .../getTaskDetails.ts "$u" || echo "none of the requested tasks are unblocked"',
        why: 'Shell composition of two scripts with an empty-result guard. No model involvement.' },
      { id: 'tt3', label: 'prepareTasks.ts: briefs, grouping, worktrees, args', lines: '10', kind: 'det', cost: 'med',
        excerpt: '- pipeline args: !`node .../prepareTasks.ts` \'$ARGUMENTS\'',
        why: 'The load-bearing deterministic step. selectRequestedTasks gates on files[], writeTaskBriefFile writes plans/brief-N.md with full file contents, groupTasksByFileOverlap runs union-find over files[], createWorktreeForGroup runs git worktree add -b task-group-N per group, and the WorkflowArguments JSON is printed for the Workflow call. All of it before a single token is spent.' },
      { id: 'tt4', label: 'skip BLOCKED tasks', lines: '14', kind: 'det', cost: 'fast',
        excerpt: 'Do not work on any task reported as BLOCKED ... report its open blockers and move on',
        why: 'Mechanical filter over tt1 output.' },
      { id: 'tt5', label: 'invoke /ponytail:ponytail ultra', lines: '16', kind: 'det', cost: 'fast',
        excerpt: 'Invoke `/ponytail:ponytail ultra`.',
        why: 'Fixed skill load. Also repeated inside every planner and worker prompt.' },
      { id: 'tt6', label: 'Verification: cross-reference codebase and git log', lines: '20-23', kind: 'int', cost: 'slow', hot: true,
        excerpt: 'Cross-reference the task with the codebase to determine if the task is still relevant ... Use the git history and recent commits (over the last 3 days) to confirm/deny the existence of the unblocked tasks',
        why: 'Unbounded reads, skipped entirely when the caller passes valid — which pick-a-task always tells the user to do. So the expensive path is the one nobody takes, and when it does run nothing bounds it.',
        rewrite: 'A relevance.ts that runs git log --since=3.days --name-only, intersects it with each task files[], and prints touched/untouched per task. The model then answers yes/no per task instead of reading the repo.' },
      { id: 'tt7', label: 'Call Workflow → 4-phase pipeline', lines: '25-26', kind: 'agent', cost: 'xslow', drill: 'workflow',
        excerpt: 'Call Workflow with scriptPath ".../tackle-tasks.workflow.js" and args set to the pipeline args JSON printed above, verbatim.',
        why: 'Where essentially all wall-clock lives. Click through to the phase breakdown.' },
      { id: 'tt8', label: 'present results, ask every clarification', lines: '28-30', kind: 'int', cost: 'xslow',
        excerpt: 'Present merged, conflicts, needsClarification and blocked to the user. Ask every needsClarification question with AskUserQuestion. ONLY after the user approves, invoke close-tasks',
        why: 'Human-bound approval gate. Deliberate.' },
      { id: 'tt9', label: 'invoke close-tasks once for all merged', lines: '34-36', kind: 'det', cost: 'fast',
        excerpt: 'Close every task that ... was completed successfully ... with **one** invocation of the `close-tasks` skill for all of them.',
        why: 'Dispatch with a fully specified argument format. Batched by design.' },
      { id: 'tt10', label: 'invoke create-task if the user asks', lines: '38', kind: 'int', cost: 'fast',
        excerpt: 'If the user requests adding tasks, invoke the `create-task` skill once per task — never edit `tasks.json` directly.',
        why: 'Conditional dispatch.' },
      { id: 'tt11', label: 'commit messages via Sonnet 5 subagent', lines: '42-46', kind: 'agent', cost: 'med',
        excerpt: 'Use a single subagent running `Sonnet 5` (fall back to `Opus 5` ...): give it the staged diff of every affected repo ... generate, per repo, a short (40 words or less) single-sentence summary',
        why: 'One extra agent spawn at the very end. The diff collection command is already exact; only the summarising needs a model.' },
    ],
  },

  workflow: {
    title: 'tackle-tasks.workflow.js',
    file: 'skills/tackle-tasks/tackle-tasks.workflow.js',
    blurb: 'Plan → Implement → Typecheck per group as an overlapping pipeline, then one merge. Groups are file-disjoint, so they pipeline independently; tasks inside a group share a worktree, so they do not.',
    steps: [
      { id: 'wf0', label: 'parse args, log group and task counts', lines: '12-17, 146', kind: 'det', cost: 'fast',
        excerpt: 'log(`${GROUPS.length} group(s), ${GROUPS.reduce((n, g) => n + g.tasks.length, 0)} task(s)`)',
        why: 'Date.now() and Math.random() are unavailable in workflow scripts (they would break resume caching), which is why runId is generated back in prepareTasks.ts.' },
      { id: 'wf1', label: 'Plan — one planner agent per task', lines: '74-76', kind: 'agent', cost: 'slow', edge: 'per group',
        excerpt: 'return parallel(group.tasks.map((t) => () => runPlanner(t)))',
        why: 'True fan-out: every task in a group is planned concurrently, so the stage costs one planner latency, not N. The prompt is tight — "Read ONLY this brief file (do not read any other file)" and "Do not change any source file" — so the planner cannot wander.',
        rewrite: 'Nothing to tighten in the prompt. The lever is the model: planners are pure reasoning over a pre-assembled brief, a good candidate for planModel downgrade.' },
      { id: 'wf2', label: 'reconcile plans, synthesize missing results', lines: '107-116', kind: 'det', cost: 'fast',
        excerpt: 'if (!planByNumber.has(t.number)) planByNumber.set(t.number, { status: \'needs-clarification\', question: \'planner returned no result\' })',
        why: 'Null-safety for killed or errored planners, in plain code between stages. Correct place for it.' },
      { id: 'wf3', label: 'Implement — workers, SERIAL within a group', lines: '118-121', kind: 'agent', cost: 'xslow', hot: true,
        excerpt: 'for (const t of plannedTasks) { const result = await runWorker(t, group, ...) }',
        why: 'The dominant wall-clock sink. N tasks in a group cost N × up to 10 minutes, strictly sequential, because they share one git worktree. Grouping is by file overlap, so a group of 5 tasks that merely touch one common file serializes all 5 — with no parallelism recovered anywhere.',
        rewrite: 'Give each task its own worktree instead of each group, and let files[] overlap be resolved at merge time rather than by serializing up front. Groups then exist only to order merges. Costs more worktrees; buys back the plugin single biggest serialization.' },
      { id: 'wf4', label: 'one-pass requeue for partial results', lines: '123-129', kind: 'agent', cost: 'slow', edge: 'if partial',
        excerpt: 'const note = `A previous worker finished part of this plan; still remaining: ${r.remaining.join(\'; \')}. Check the file state before redoing anything.`',
        why: 'A partial worker doubles that task cost. Exactly one retry — deliberately not a loop, which is the right call.' },
      { id: 'wf5', label: 'Typecheck — one low-effort agent per group', lines: '135-140', kind: 'agent', cost: 'med', edge: 'per group',
        excerpt: 'cd ${group.worktree} and run: ${TYPECHECK_COMMAND} ... Report only — do not edit any file.',
        why: 'An LLM round trip whose entire job is to run one command and report a boolean. The workers already ran the same typecheck themselves.',
        rewrite: 'Fold it into the merge script: mergeTaskWorktrees.ts can run the typecheck per worktree before merging and refuse the merge on failure. Removes G agent spawns and makes the gate real instead of advisory.' },
      { id: 'wf6', label: 'BARRIER — all groups finish before merge', lines: '147', kind: 'det', cost: 'fast', hot: true,
        excerpt: 'await pipeline(GROUPS, planStage, implementStage, typecheckStage)',
        why: 'Groups overlap through the three stages, but nothing merges until every group has cleared all three. One slow group holds every other group finished work uncommitted.',
        rewrite: 'Merge each group as it clears typecheck instead of at the end. Merges already serialize inside mergeTaskWorktrees.ts, so ordering is preserved either way — the barrier buys nothing.' },
      { id: 'wf7', label: 'Merge agent — wraps a node one-liner', lines: '167-174', kind: 'agent', cost: 'med', hot: true,
        excerpt: 'Run exactly this command and return its stdout as JSON, unmodified — do not parse, summarize, reformat, or edit it. Do not run any other command.',
        why: 'A full agent spawn, model round trip, and SubagentStop hook, to shell out to one deterministic CLI and pass its stdout through untouched. Pure overhead — and a failure mode, since the agent could still garble the JSON.',
        rewrite: 'Call mergeTaskWorktrees.ts from the workflow script directly if the harness exposes any non-agent shell path. If it truly does not, this is the cheapest possible shim and worth documenting as such right in the script.' },
      { id: 'wf8', label: 'mergeTaskWorktrees.ts — serial merge, cleanup, metrics', file: 'scripts/mergeTaskWorktrees.ts', lines: 'runAsCli', kind: 'det', cost: 'med',
        excerpt: 'git merge --no-ff <branch>; on failure git diff --name-only --diff-filter=U then git merge --abort; on success git worktree remove --force + git branch -D',
        why: 'Merges in ascending groupId order — necessarily serial, since every merge touches the same working tree. A conflict means a worker touched a file it did not declare. Appends one run record to plans/tackle-metrics.jsonl via tackleMetrics.ts.' },
    ],
  },

  'update-tasks': {
    title: 'update-tasks',
    file: 'skills/update-tasks/SKILL.md',
    blurb: 'Harvests open questions out of plans/ notes into tasks, then archives the notes.',
    steps: [
      { id: 'ut0', label: 'invoke /ponytail:ponytail ultra', lines: '7', kind: 'det', cost: 'fast',
        excerpt: 'First, invoke `/ponytail:ponytail ultra`.', why: 'Fixed skill load.' },
      { id: 'ut1', label: 'list files to process', lines: '11', kind: 'det', cost: 'fast',
        excerpt: '!`node .../extractOpenSections.ts --list`',
        why: 'Lists plans/implementation-notes-*.md and plans/handoff-*.md.' },
      { id: 'ut2', label: 'extract sections, then judge which to keep', lines: '13-17', kind: 'int', cost: 'med',
        excerpt: 'Apply judgment to the extracted text above: skip items the section itself marks as resolved (e.g. "None blocking"), and skip empty sections.',
        why: 'Extraction is a deterministic parse; the keep/skip filter is not.',
        rewrite: 'The "None blocking" case and the empty-section case are both detectable in extractOpenSections.ts. Filter them at the source and the judgment shrinks to genuinely ambiguous items.' },
      { id: 'ut3', label: 'de-duplicate against existing tasks', lines: '19-20', kind: 'int', cost: 'slow', hot: true,
        excerpt: 'check both `tasks.json` and `completedTasks.json` (titles and descriptions) for an existing task covering the same item',
        why: 'Every harvested item is compared against every task in both files, by hand, in prose. Grows with the task backlog — and the backlog only grows.',
        rewrite: 'A script that prints candidate collisions (token overlap on title plus shared paths in files[]) turns an N×M scan into a short list to adjudicate.' },
      { id: 'ut4', label: 'loop create-task per new item', lines: '22', kind: 'int', cost: 'slow',
        excerpt: 'one Skill-tool invocation per task, sequentially (each invocation injects the then-current next taskNumber)',
        why: 'Same N-round-trip shape as goal-tasks step 4. The sequential requirement exists only because nextTaskNumber.ts is re-injected per invocation.',
        rewrite: 'Same fix as goal-tasks: one batch append CLI that allocates numbers internally.' },
      { id: 'ut5', label: 'archiveProcessed.ts', lines: '24', kind: 'det', cost: 'fast',
        excerpt: 'node .../archiveProcessed.ts <the step-1 file list>',
        why: 'Moves files into plans/archived/, prints COLLISION for name clashes.' },
      { id: 'ut6', label: 'report table', lines: '26', kind: 'int', cost: 'fast',
        excerpt: 'report a short table: each archived file → the task numbers created from it',
        why: 'Report only.' },
      { id: 'ut7', label: 'commit summary via Sonnet 5 subagent', lines: '27', kind: 'agent', cost: 'med',
        excerpt: 'Use a subagent running `Sonnet 5` (fall back to `Opus 5` ...) to generate a short (40 words or less) single-sentence summary',
        why: 'One agent spawn for one sentence. Same pattern as the tackle-tasks commit step.' },
    ],
  },

  'update-task-files': {
    title: 'update-task-files',
    file: 'skills/update-task-files/SKILL.md',
    blurb: 'Backfills files[] on tasks created before the field existed. Exists entirely because create-task lets the field be omitted.',
    steps: [
      { id: 'uf1', label: 'inject repo root and task details', lines: '7-8', kind: 'det', cost: 'fast',
        excerpt: '- repo root: !`pwd`  /  - task details: !`node .../getTaskDetails.ts` \'$ARGUMENTS\'',
        why: 'pwd is injected because every path written below must be relative to it.' },
      { id: 'uf2', label: 'invoke /ponytail:ponytail ultra', lines: '10', kind: 'det', cost: 'fast',
        excerpt: 'First, invoke `/ponytail:ponytail ultra`.', why: 'Fixed skill load.' },
      { id: 'uf3', label: 'determine what each task genuinely touches', lines: '12-13, 41-42', kind: 'int', cost: 'xslow', hot: true,
        excerpt: 'List what the task genuinely touches — not the whole module, and not one file when the change spans three.',
        why: 'The most open-ended instruction in the plugin, and the highest-leverage: over-declaring serializes tasks that could run in parallel, under-declaring causes merge conflicts. The skill explains the stakes well but gives the model no tool to meet them.',
        rewrite: 'Ship a candidates step: grep the task title and description for identifiers, run git log -S on them, and print the files that actually contain them. The model picks from a real list instead of recalling paths.' },
      { id: 'uf4', label: 'path rules — exist on disk, repo-relative, include tests', lines: '19-27', kind: 'int', cost: 'med',
        excerpt: 'Every path must already exist on disk. Verify each one. A path that does not resolve silently degrades the task brief to `(missing: file not found)` at run time.',
        why: 'A hard, checkable constraint stated as prose the model must remember to honour.',
        rewrite: 'One checkTaskFiles.ts that validates every files[] entry across tasks.json and exits non-zero with the offenders. Then this section becomes "run it until it passes" — and close-tasks or a hook can enforce it too.' },
      { id: 'uf5', label: 'edit tasks.json in place', lines: '51-59', kind: 'int', cost: 'med',
        excerpt: 'Preserve every existing field, key order, task order, and task number. Do not reformat, reorder, renumber, or drop any entry.',
        why: 'Five separate do-not rules exist only because a model is hand-editing JSON.',
        rewrite: 'setTaskFiles.ts <n> <paths...> makes every one of those rules structurally impossible.' },
      { id: 'uf6', label: 'verify before reporting', lines: '61-65', kind: 'int', cost: 'med',
        excerpt: 'The task count in `tasks.json` is unchanged. Every path you added exists: check each one on disk. `git diff` shows changes to `tasks.json` only.',
        why: 'A three-point self-check, done by hand, that is three shell commands.',
        rewrite: 'Exactly the checkTaskFiles.ts from uf4 plus git diff --name-only. Self-verification by prose is the least reliable determinism in the plugin.' },
      { id: 'uf7', label: 'report table plus undeterminable list', lines: '67-70', kind: 'int', cost: 'fast',
        excerpt: 'A table of task number to files, then a separate list of the task numbers you left without a `files` field',
        why: 'Report only.' },
    ],
  },

})
