Object.assign(GRAPH.skills, {

  'pick-a-task': {
    title: 'pick-a-task',
    file: 'skills/pick-a-task/SKILL.md',
    blurb: 'Ranks open tasks by ease and prints the exact command to tackle them. Read-only.',
    steps: [
      { id: 'pa1', label: 'inject open task list', lines: '8', kind: 'det', cost: 'fast',
        excerpt: 'Open tasks: !`node .../getTaskDetails.ts | grep ^OPEN`',
        why: 'Runs at prompt-assembly time. No model involvement.' },
      { id: 'pa2', label: 'inject blocked status', lines: '10', kind: 'det', cost: 'fast',
        excerpt: 'Blocked status: !`node .../checkBlockers.ts`',
        why: 'Same — pure JSON read, printed into the prompt.' },
      { id: 'pa3', label: 'read code to judge scope of every open task', lines: '12', kind: 'int', cost: 'slow', hot: true,
        excerpt: 'Compare each open task above against the current state of the project ... check the relevant code/files to judge scope (already partly done? one-file change? decision-only?)',
        why: 'Unbounded. With 50 open tasks the model may open dozens of files, and nothing caps how deep it goes. This is the entire cost of the skill.',
        rewrite: 'Score tasks in a script first: files[] length, blockedBy depth, description length, and whether git log touched the declared files recently. Print a ranked shortlist and let the model read code for only the top N.' },
      { id: 'pa4', label: 'exclude BLOCKED tasks', lines: '14', kind: 'det', cost: 'fast',
        excerpt: 'Exclude any task reported as BLOCKED in the "Blocked status" above',
        why: 'Mechanical filter over script output — deterministic in substance, but still executed by the model.',
        rewrite: 'checkBlockers.ts already has an --unblocked flag (tackle-tasks uses it). Use it here too and the filter disappears from the prose.' },
      { id: 'pa5', label: 'rank N easiest, justify under 70 words', lines: '16', kind: 'int', cost: 'med',
        excerpt: 'Pick the N easiest/simplest open tasks, ordered easiest first ... under 70 words per task.',
        why: 'Genuine judgment, and cheap once pa3 has already paid for the reading.' },
      { id: 'pa6', label: 'print fixed handoff command', lines: '18-21', kind: 'det', cost: 'fast',
        excerpt: 'End your report with exactly: `start a session with: ...` / `prompt: "/tackle-tasks [<N,...>] valid"`',
        why: 'Fully specified output format, including the valid flag that lets the next skill skip its own verification.' },
    ],
  },

  'create-task': {
    title: 'create-task',
    file: 'skills/create-task/SKILL.md',
    blurb: 'The only sanctioned writer of tasks.json. Called directly, by goal-tasks, and by update-tasks.',
    steps: [
      { id: 'ct1', label: 'inject next task number', lines: '7', kind: 'det', cost: 'fast',
        excerpt: 'taskNumber to use: !`node .../nextTaskNumber.ts`',
        why: 'max(taskNumber)+1 across both files. Seeds .taskTools/ on first use.' },
      { id: 'ct2', label: 'decide if the description is actionable', lines: '11', kind: 'int', cost: 'med',
        excerpt: 'Decide whether that description is actionable later without this conversation context ... If not, invoke AskUserQuestion ... or /grill-me',
        why: 'A real judgment call, and it can block on the human. Unavoidable at this boundary.' },
      { id: 'ct3', label: 'append one object using taskTemplate.json', lines: '13-17', kind: 'int', cost: 'med',
        excerpt: '```json\\n!`cat .../create-task/template/taskTemplate.json`\\n```',
        why: 'Template is injected deterministically; the field values and the JSON edit are the model.',
        rewrite: 'A writeTask.ts CLI taking title/description/files/blockedBy as args would make the append atomic and remove the append-as-LAST-element / never-reorder rules that exist only because a model is editing JSON by hand.' },
      { id: 'ct4', label: 'populate files[]', lines: '19', kind: 'int', cost: 'med', hot: true,
        excerpt: 'Populate `files` with the repo-relative paths the task will touch ... If they genuinely cannot be determined, omit the field entirely rather than guessing.',
        why: 'Load-bearing far downstream: files[] is the ownership fence for workers AND the concurrency key for grouping. Omitting it here is what later forces update-task-files to exist, and what collapses tackle-tasks parallelism to one group.',
        rewrite: 'Verify each path exists on disk at write time (same check update-task-files performs after the fact) and refuse silently-wrong paths here, where the context to fix them is still live.' },
      { id: 'ct5', label: 'add handoffFilePaths if named', lines: '21', kind: 'int', cost: 'fast',
        excerpt: 'If the request names the source note/handoff file(s) ... include "handoffFilePaths"',
        why: 'Conditional field copy. Trivial.' },
      { id: 'ct6', label: 'append number to spec item Tasks: line', lines: '23', kind: 'int', cost: 'fast',
        excerpt: 'If `specs/SPEC.md` exists and this task belongs to one of its spec items, append the task number to that item Tasks: line.',
        why: 'Requires matching the task to a spec item — small but genuine interpretation.' },
      { id: 'ct7', label: 'confirm number and title', lines: '27', kind: 'int', cost: 'fast',
        excerpt: 'Finally, confirm to the user: the task number and title that were added.',
        why: 'Report only.' },
    ],
  },

  'goal-tasks': {
    title: 'goal-tasks',
    file: 'skills/goal-tasks/SKILL.md',
    blurb: 'Interview to spec to ordered tasks. The only skill with no scripts at all — six prose steps, two of them human-bound.',
    steps: [
      { id: 'gt1', label: 'interview the user for the real goal', lines: '10', kind: 'int', cost: 'xslow',
        excerpt: '1. Interview the user to find the real goal of this project.',
        why: 'Human-bound. Wall-clock here is the user, not the model — correctly left interpretive.' },
      { id: 'gt2', label: 'draft specs/SPEC.md from template', lines: '12', kind: 'int', cost: 'slow',
        excerpt: '2. Draft the spec at `specs/SPEC.md` ... following the template at .../templates/SPEC.md. Spec items must be concrete and verifiable via tests.',
        why: 'Template supplies the scaffold; every word of content is generated.' },
      { id: 'gt3', label: 'confirm with the user before creating tasks', lines: '14', kind: 'int', cost: 'xslow',
        excerpt: '3. Confirm the goal, spec items, and key decisions with the user. Do not create any tasks until the user agrees.',
        why: 'A deliberate human gate. Keep it.' },
      { id: 'gt4', label: 'loop /create-task per task', lines: '16', kind: 'int', cost: 'slow', hot: true,
        excerpt: '4. Use `/create-task` to create granular tasks ... Each task should be completable in under 20 minutes and at most ~200 lines of code',
        why: 'N sequential full skill invocations, each re-reading the template and re-deciding actionability. For a 12-item spec that is 12 round trips to add 12 JSON objects.',
        rewrite: 'Have the model emit the whole task list once, then a createTasks.ts CLI appends them in one pass with numbering handled internally. Same guarantees, one round trip.' },
      { id: 'gt5', label: 'backfill task numbers into spec', lines: '18', kind: 'int', cost: 'fast',
        excerpt: '5. Backfill the created task numbers into each spec item Tasks: line.',
        why: 'Bookkeeping edit. Would fall out for free if gt4 were scripted.' },
      { id: 'gt6', label: 'stage, do not commit', lines: '20', kind: 'det', cost: 'fast',
        excerpt: '6. Stage `specs/SPEC.md` and `tasks.json`. Do not commit.',
        why: 'Fixed git add of two known paths.' },
    ],
  },

  'close-tasks': {
    title: 'close-tasks',
    file: 'skills/close-tasks/SKILL.md',
    blurb: 'The regression gate. Runs full verification once for a batch, then archives tasks and unblocks dependents.',
    steps: [
      { id: 'cl1', label: 'inject task details', lines: '8', kind: 'det', cost: 'fast',
        excerpt: 'tasks to close: !`node .../getTaskDetails.ts` \'$ARGUMENTS\'',
        why: 'Reads both task files. The prose right below it tells the model how to detect a malformed argument array and re-run.' },
      { id: 'cl2', label: 'full verification, fix, re-run until green', lines: '14', kind: 'int', cost: 'xslow', hot: true,
        excerpt: 'run the project verification once for the whole batch: typecheck plus the full test suite ... If failures trace to the work being closed, fix them, re-stage the fixes, and re-run until green',
        why: 'The single most expensive step in the plugin: an unbounded fix-and-retry loop with no iteration cap, no time budget, and no definition of when to give up. Every other verification in the plugin was deliberately deferred to here, so this is where it all lands.',
        rewrite: 'Bound it. A verify.ts that runs typecheck plus tests, caps retries at 2, and returns structured failures gives the model a decision instead of a loop. State the cap in the prose the way the worker prompt already states its 10-minute budget.' },
      { id: 'cl3', label: 'move objects and add closure fields', lines: '16', kind: 'int', cost: 'slow',
        excerpt: 'move its object from `tasks.json` to `completedTasks.json`, adding a `completionDate` (today), `commitHashes` (search git history for the resolving commits ...), and a short `closureNote`',
        why: 'Two-file JSON surgery plus a git-history search per task, all done by hand by the model.',
        rewrite: 'closeTasks.ts <numbers> <notes> can do the move, the date, and git log --oneline --grep="task N" for the hashes. Leaves the model authoring only closureNote text.' },
      { id: 'cl4', label: 'skip already-completed or missing', lines: '18', kind: 'det', cost: 'fast',
        excerpt: 'Skip tasks already COMPLETED or not found, and say so.',
        why: 'Mechanical, decided from the injected listing.' },
      { id: 'cl5', label: 'unblockDependents.ts', lines: '20', kind: 'det', cost: 'fast',
        excerpt: 'node .../unblockDependents.ts \'<the task numbers as a no-space JSON array>\'',
        why: 'Removes closed numbers from every remaining blockedBy array and reports what it freed.' },
      { id: 'cl6', label: 'stage and suggest a commit message', lines: '22', kind: 'int', cost: 'fast',
        excerpt: 'Stage the changes but do not commit. Provide a short commit message ... similar to "Closed tasks [268,270,281]"',
        why: 'Format is fully specified — one substitution away from being a script.' },
      { id: 'cl7', label: 'mark spec items done', lines: '24', kind: 'int', cost: 'fast',
        excerpt: 'If a spec document references these task numbers, mark those items done in the spec.',
        why: 'Conditional edit, requires matching numbers to spec lines.' },
    ],
  },

  'view-task': {
    title: 'view-task',
    file: 'skills/view-task/SKILL.md',
    blurb: 'The reference implementation: a skill that costs zero tokens because a hook answers before the model runs.',
    steps: [
      { id: 'vt1', label: 'skill body is an explicit no-op', lines: '8', kind: 'det', cost: 'fast',
        excerpt: 'do nothing. don\'t even acknowledge what the user typed. just let the UserPromptSubmit hook do its thing.',
        why: 'The real work is viewTaskHook.ts, which returns a block decision with the formatted task as the reason. No model turn, no tokens, no latency beyond one node spawn.',
        rewrite: 'Nothing to fix — this is the pattern the other read-only skills should copy.' },
    ],
  },

})
