%%{init: {"flowchart": {"wrappingWidth": 100000}}}%%
flowchart TD

B_TASK_STARTED[task started]

%% define "successfully" per task

Q_TASK_SUCCEEDED{did the model complete the task successfully?}
Q_CHOICE_TASK_SUCCEEDED_NO[No]
Q_CHOICE_TASK_SUCCEEDED_YES[Yes]

Q_MODEL_KNEW_ENOUGH{Did the model know enough?}
Q_CHOICE_MODEL_KNEW_ENOUGH_NO[No]
Q_CHOICE_MODEL_KNEW_ENOUGH_YES[Yes]
B_CHANGE_MODEL["change /model"]

Q_TRIED_HARD_ENOUGH{Did the model try hard enough?}
Q_CHOICE_TRIED_HARD_ENOUGH_NO[No]
Q_CHOICE_TRIED_HARD_ENOUGH_YES[Yes]
B_CHANGE_EFFORT["change /effort"]
B_TRY_TASK_AGAIN[try the task again]

Q_KNOW_WHY_FAILED{do you know why the task was not completed successfully?}
Q_CHOICE_KNOW_WHY_FAILED_NO[No]
Q_CHOICE_KNOW_WHY_FAILED_YES[Yes]
B_FIND_OUT_WHY[find out why]
B_UPDATE_INSTRUCTIONS[update the task instructions]
B_KEEP_MODEL["don't change the model"]
B_KEEP_EFFORT["don't change the effort"]

Q_COULD_BE_CHEAPER{could the task cost have been cheaper or done quicker?}
Q_CHOICE_COULD_BE_CHEAPER_NO[No]
Q_CHOICE_COULD_BE_CHEAPER_YES[Yes]
B_NEXT_TASK[move on to the next task]
B_TRY_LOWER["try the next task that has the same complexity/difficulty level with a lower effort or model"]

B_TASK_STARTED --> Q_TASK_SUCCEEDED

Q_TASK_SUCCEEDED --> Q_CHOICE_TASK_SUCCEEDED_NO --> Q_MODEL_KNEW_ENOUGH
Q_TASK_SUCCEEDED --> Q_CHOICE_TASK_SUCCEEDED_YES --> Q_COULD_BE_CHEAPER

Q_MODEL_KNEW_ENOUGH --> Q_CHOICE_MODEL_KNEW_ENOUGH_NO --> B_CHANGE_MODEL --> B_TRY_TASK_AGAIN
Q_MODEL_KNEW_ENOUGH --> Q_CHOICE_MODEL_KNEW_ENOUGH_YES --> Q_TRIED_HARD_ENOUGH

Q_TRIED_HARD_ENOUGH --> Q_CHOICE_TRIED_HARD_ENOUGH_NO --> B_CHANGE_EFFORT --> B_TRY_TASK_AGAIN
Q_TRIED_HARD_ENOUGH --> Q_CHOICE_TRIED_HARD_ENOUGH_YES --> Q_KNOW_WHY_FAILED

Q_KNOW_WHY_FAILED --> Q_CHOICE_KNOW_WHY_FAILED_NO --> B_FIND_OUT_WHY --> B_UPDATE_INSTRUCTIONS
Q_KNOW_WHY_FAILED --> Q_CHOICE_KNOW_WHY_FAILED_YES --> B_UPDATE_INSTRUCTIONS --> B_KEEP_MODEL --> B_KEEP_EFFORT --> B_TRY_TASK_AGAIN

Q_COULD_BE_CHEAPER --> Q_CHOICE_COULD_BE_CHEAPER_NO --> B_NEXT_TASK
Q_COULD_BE_CHEAPER --> Q_CHOICE_COULD_BE_CHEAPER_YES --> B_TRY_LOWER

B_TRY_TASK_AGAIN --> B_TASK_STARTED
B_TRY_LOWER --> B_TASK_STARTED
B_NEXT_TASK --> B_TASK_STARTED