// Writes the tackle-tasks workflow: one agent() per hook stop, from the preamble's first box to a stop.
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildHookOutputSchema } from "./buildRunStepSchemas.ts";
import type { StepConfig } from "./generateSteps.ts";

const PROJECT_ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const DEFAULT_CONFIG_FILE = join(PROJECT_ROOT, "scripts/tackle-tasks/diagram-steps.json");
// RETIRED (task 10): no code writes the shared plugin workflow file anymore; every task generates its own under the target project's .taskTools/workflows/<N>/.
// export const WORKFLOW_FILE = join(PROJECT_ROOT, "skills/tackle-tasks/tackle-tasks.workflow.js");
export const START_STEP = "pipeline-preambleStatusCheck.mmd::PREAMBLE_STATUS_CHECK";

// Every regenerated START_STEP must resolve to a real box, or the workflow starts nowhere.
export function assertStartStepIsInConfig(config: StepConfig, startStep: string): void {
    const allStepKeys = new Set<string>();
    for (const [diagram, entries] of Object.entries(config)) {
        for (const entry of entries) {
            allStepKeys.add(`${diagram}::${entry.box}`);
        }
    }
    if (!allStepKeys.has(startStep)) {
        throw new Error(`START_STEP ${startStep} is not a key in the config`);
    }
}

export function buildWorkflowScript(taskNumber: number, configFile: string): string {
    const config = JSON.parse(readFileSync(configFile, "utf8")) as StepConfig;
    assertStartStepIsInConfig(config, START_STEP);
    const hookOutputSchemaText = JSON.stringify(buildHookOutputSchema(), null, 4);
    return `export const meta = {
    name: 'Tackle-task ${taskNumber}',
    description: 'Tackle tasks.json:[N]',
}
// Generated by scripts/tackle-tasks/generateWorkflow.ts. Do not edit this file.

const START_STEP = '${START_STEP}'
const TASK_NUMBER = ${taskNumber}
// One shape for every pass: the answer to a prompt lives in the packet file, never in this object.
const HOOK_OUTPUT_SCHEMA = ${hookOutputSchemaText}

// Required: the task number and the tasks.json the preamble reads. args.startingBlock is optional.
if (!Number.isInteger(args?.task) || !args?.tasksFile) {
    throw new Error('tackle-tasks needs args.task (a task number) and args.tasksFile (the path of tasks.json)')
}
if (args.task !== TASK_NUMBER) {
    throw new Error(\`this workflow file only runs task \${TASK_NUMBER}, not \${args.task}\`)
}

function createPromptForAgent(blockToRun, input) {
    // The block output belongs to the hook. Saying so stops the agent authoring one of its own.
    const command = \`/run-step \${blockToRun} \${JSON.stringify(input)}\`
    return [
        \`COMMAND: \\\`\${command}\\\`\`,
        'invoke COMMAND and follow instructions.',
        'Return the object that the hook returns, verbatim. Do not modify or mutate that object.',
    ].join('\\n')
}

let blockToRun = args.startingBlock ?? START_STEP
let input = { taskNumber: args.task, tasksFile: args.tasksFile }
// Only ran accumulates across passes. Everything else belongs to the pass that produced it.
const ran = []
let currentDiagram = ''
while (true) {
    // One progress group per diagram visit, titled by the block that starts it.
    const diagram = blockToRun.split('::')[0]
    const blockName = blockToRun.split('::').pop()
    if (diagram !== currentDiagram) {
        phase(blockName)
        currentDiagram = diagram
    }
    const prompt = createPromptForAgent(blockToRun, input)
    const result = await agent(prompt, { label: \`run-step:\${blockName}\`, schema: HOOK_OUTPUT_SCHEMA })

    // API error. the only shape agent() produces that is not the hook output.
    if (result === null) {
        return { ok: false, ran, errors: [\`\${blockName}: agent died or was skipped\`], prompt, outcome: null }
    }
    // A string here is an agent that skipped StructuredOutput; keep its text, or the real error is lost.
    if (typeof result === 'string') {
        return { ok: false, ran, errors: [\`\${blockName}: agent answered with text, not the hook output\`, result], prompt, outcome: null }
    }
    ran.push(...result.ran)

    // script exited non-zero, block was unknown, or output came back as a string.
    if (result.ok === false) {
        return { ok: false, ran, errors: result.errors, prompt, outcome: result.outcome, report: result.report }
    }

    // agent never ran /run-step, made up fields, or reworded them; hook threw or returned nothing.
    if (result.ran.length === 0) {
        return { ok: false, ran, errors: [\`\${blockName}: agent answered without a hook output/payload/packet\`], prompt, outcome: null }
    }

    // the hook says nothing follows the block the walk stopped at, so this run is done.
    if (result.outcome.next === null) {
        return { ok: true, ran, errors: [], prompt, outcome: result.outcome }
    }
    blockToRun = result.outcome.next
    // outcome.payload is the packet file the next block starts from; a prompt answer was written into it.
    input = { packetFile: result.outcome.payload }
}
`;
}

export function generateWorkflow(workflowFile: string, taskNumber: number, configFile: string): string {
    const workflowScript = buildWorkflowScript(taskNumber, configFile);
    mkdirSync(dirname(workflowFile), { recursive: true });
    // Written to a sibling temp path and renamed into place, so a reader mid-generation never sees a truncated file.
    const temporaryFile = `${workflowFile}.${process.pid}.tmp`;
    writeFileSync(temporaryFile, workflowScript);
    renameSync(temporaryFile, workflowFile);
    return workflowScript;
}

// RETIRED (task 10): see the note at the WORKFLOW_FILE declaration above.
// if (process.argv[1] === fileURLToPath(import.meta.url)) {
//     generateWorkflow(WORKFLOW_FILE);
// }
