// Writes the run-step workflow from steps.json, with one schema per block built from that block's template.
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { BlockTemplate, StepConfig } from "./generateSteps.ts";
import { getSchemaFromTemplate } from "./templateSchema.ts";

const PROJECT_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const CONFIG_FILE = join(PROJECT_ROOT, "scripts/steps.json");
const WORKFLOW_FILE = join(PROJECT_ROOT, ".claude/workflows/run-step.workflow.js");

export type BlockSchema = {
    diagram: string;
    box: string;
    name: string;
    schema: Record<string, unknown>;
};

export function getBlockSchemaName(box: string): string {
    return `BLOCK_${box}_SCHEMA`;
}

// One entry per block, so every schema in the generated file is named after the block it came from.
export function buildBlockSchemas(config: StepConfig, projectRoot: string): BlockSchema[] {
    const blockSchemas: BlockSchema[] = [];
    for (const [diagram, entries] of Object.entries(config)) {
        for (const entry of entries) {
            const templateText = readFileSync(join(projectRoot, entry.template), "utf8");
            const template = JSON.parse(templateText) as BlockTemplate;
            blockSchemas.push({
                diagram,
                box: entry.box,
                name: getBlockSchemaName(entry.box),
                schema: getSchemaFromTemplate(template.output),
            });
        }
    }
    return blockSchemas;
}

// The hook always returns this envelope. buildPossibleSchemas fills in output, so it starts empty.
export function buildWalkResultSchema(): Record<string, unknown> {
    return {
        type: "object",
        properties: {
            ok: { type: "boolean" },
            ran: { type: "array", items: { type: "string" } },
            stoppedAt: { type: "string" },
            why: { type: "string" },
            isTerminal: { type: "boolean" },
            report: { type: "string" },
            output: { anyOf: [] },
        },
        required: ["ok", "ran", "stoppedAt", "why", "isTerminal", "report", "output"],
        additionalProperties: false,
    };
}

export function getFirstBox(config: StepConfig): string {
    const firstEntries = Object.values(config)[0] ?? [];
    return firstEntries[0]?.box ?? "";
}

function buildBlockSchemaText(blockSchemas: BlockSchema[]): string {
    const declarations = blockSchemas.map(blockSchema => {
        const schemaText = JSON.stringify(blockSchema.schema, null, 4);
        return `const ${blockSchema.name} = ${schemaText}`;
    });
    return declarations.join("\n\n");
}

function buildBlockSchemaMapText(config: StepConfig): string {
    const lines: string[] = ["const BLOCK_SCHEMAS = {"];
    for (const [diagram, entries] of Object.entries(config)) {
        lines.push(`    ${JSON.stringify(diagram)}: {`);
        for (const entry of entries) {
            lines.push(`        ${entry.box}: ${getBlockSchemaName(entry.box)},`);
        }
        lines.push("    },");
    }
    lines.push("}");
    return lines.join("\n");
}

export function buildWorkflowScript(config: StepConfig, projectRoot: string): string {
    const blockSchemas = buildBlockSchemas(config, projectRoot);
    const blockSchemaText = buildBlockSchemaText(blockSchemas);
    const blockSchemaMapText = buildBlockSchemaMapText(config);
    const walkResultSchemaText = JSON.stringify(buildWalkResultSchema(), null, 4);
    const firstBoxText = JSON.stringify(getFirstBox(config));
    return `// Generated by scripts/generateWorkflow.ts from scripts/steps.json. Do not edit this file.
export const meta = {
    name: 'run-step',
    description: 'Run one diagram block and every block that follows it, through the run-step hook',
    phases: [{ title: 'Run', detail: 'one agent per pass, until a block is terminal or reports back' }],
}

// One schema per block, built from that block's output template, named after the block.
${blockSchemaText}

// Every block schema, keyed by diagram then box. buildPossibleSchemas picks from this.
${blockSchemaMapText}

// The envelope the hook always returns. Only output changes, so buildPossibleSchemas fills it in.
const WALK_RESULT_SCHEMA = ${walkResultSchemaText}

const FIRST_BOX = ${firstBoxText}

// placeholder: names the block the next agent starts at. A null result means the first block.
function getNextStep(result) {
    return FIRST_BOX
}

// placeholder: picks the schemas reachable from stepToStartAt, up to the first branching point, plus error shapes.
function buildPossibleSchemas(stepToStartAt, blockSchemas) {
    return WALK_RESULT_SCHEMA
}

phase('Run')

// ponytail: getNextStep always answers FIRST_BOX, so this loop never ends. It ends once getNextStep is real.
let result = null
while (true) {
    const stepToStartAt = getNextStep(result)
    const possibleSchemas = buildPossibleSchemas(stepToStartAt, BLOCK_SCHEMAS)
    result = await agent(stepToStartAt, { label: \`run-step:\${stepToStartAt}\`, schema: possibleSchemas })
    if (result.isTerminal) break
    if (result.report) break
}

// a terminal block, or something to hand back to the orchestrating agent
return result
`;
}

export function generateWorkflow(configFile: string, workflowFile: string, projectRoot: string): string {
    const config = JSON.parse(readFileSync(configFile, "utf8")) as StepConfig;
    const workflowScript = buildWorkflowScript(config, projectRoot);
    mkdirSync(dirname(workflowFile), { recursive: true });
    writeFileSync(workflowFile, workflowScript);
    return workflowScript;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    generateWorkflow(CONFIG_FILE, WORKFLOW_FILE, PROJECT_ROOT);
    console.log(`wrote ${WORKFLOW_FILE.slice(PROJECT_ROOT.length + 1)}`);
}
