// Writes the tackle-tasks workflow: one agent() per hook stop, from the preamble's first box to a stop.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildAgentSchema } from "./buildRunStepSchemas.ts";
import type { StepConfig } from "./generateSteps.ts";

const PROJECT_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const CONFIG_FILE = join(PROJECT_ROOT, "scripts/steps.json");
export const WORKFLOW_FILE = join(PROJECT_ROOT, "skills/tackle-tasks/tackle-tasks.workflow.js");
export const START_STEP = "pipeline-preambleStatusCheck.mmd::PREAMBLE_TASK_NUMBER_INPUT";

export function buildWorkflowScript(): string {
    const config = JSON.parse(readFileSync(CONFIG_FILE, "utf8")) as StepConfig;
    // The first pass may stop at any block, so its schema names every one. Each later pass gets the list the hook filtered.
    const firstPassSchemaText = JSON.stringify(buildAgentSchema(config, PROJECT_ROOT, START_STEP), null, 4);
    return `export const meta = {
    name: 'tackle-tasks',
    description: 'Tackle one task from tasks.json: every diagram block from the preamble to a stop, through the run-step hook',
}
// Generated by scripts/generateWorkflow.ts. Do not edit this file.

const START_STEP = '${START_STEP}'
const FIRST_PASS_SCHEMA = ${firstPassSchemaText}

// Required: the task number and the tasks.json the preamble reads.
if (!Number.isInteger(args?.task) || !args?.tasksFile) {
    throw new Error('tackle-tasks needs args.task (a task number) and args.tasksFile (the path of tasks.json)')
}

function createPromptForAgent(blockToRun, input) {
    // The envelope belongs to the hook. Saying so stops the agent authoring one of its own.
    let inputString = JSON.stringify(input)
    if (inputString === '{}') {
        inputString = ''
    }
    const command = \`/run-step \${blockToRun} \${inputString}\`.trim()
    return [
        \`COMMAND: \\\`\${command}\\\`\`,
        'invoke COMMAND and follow instructions.',
        'Return the object that the hook returns, verbatim. Do not modify or mutate that object.',
        'The only exception: if outcome.scriptSignal is "prompt", follow outcome.payload.prompt and put your answer in outcome.payload as the object the schema requires.',
    ].join('\\n')
}

let blockToRun = START_STEP
let schema = FIRST_PASS_SCHEMA
// A block sees only the pass before it, so the last payload has to be carried forward by hand.
let input = { taskNumber: args.task, tasksFile: args.tasksFile }
// The last payload that was not a prompt block's answer, merged back in after a prompt pass.
let lastPacket = {}
// Only ran accumulates across passes. Everything else belongs to the pass that produced it.
const ran = []
while (true) {
    // Grouped by diagram, so crossing a :: seam opens a new group in the progress tree.
    phase(blockToRun.split('::')[0])
    const prompt = createPromptForAgent(blockToRun, input)
    const result = await agent(prompt, { label: \`run-step:\${blockToRun}\`, schema })

    // API error. the only shape agent() produces that is not the envelope.
    if (result === null) {
        return { ok: false, ran, errors: [\`\${blockToRun}: agent died or was skipped\`], prompt, outcome: null }
    }
    ran.push(...result.ran)

    // script exited non-zero, block was unknown, or output came back as a string.
    if (result.ok === false) {
        return { ok: false, ran, errors: result.errors, prompt, outcome: result.outcome }
    }

    // agent never ran /run-step, made up fields, or reworded them; hook threw or returned nothing.
    if (result.ran.length === 0) {
        return { ok: false, ran, errors: [\`\${blockToRun}: agent answered without a hook envelope\`], prompt, outcome: null }
    }

    // the hook says nothing follows the block the walk stopped at, so this run is done.
    if (result.outcome.workflowSignal === 'done') {
        return { ok: true, ran, errors: [], prompt, outcome: result.outcome }
    }
    blockToRun = result.outcome.next
    schema = result.outcome.schema
    if (result.outcome.scriptSignal === 'prompt') {
        input = { ...lastPacket, ...result.outcome.payload }
    } else {
        lastPacket = result.outcome.payload
        input = result.outcome.payload
    }
}
`;
}

export function generateWorkflow(workflowFile: string): string {
    const workflowScript = buildWorkflowScript();
    mkdirSync(dirname(workflowFile), { recursive: true });
    writeFileSync(workflowFile, workflowScript);
    return workflowScript;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    generateWorkflow(WORKFLOW_FILE);
    console.log(`wrote ${WORKFLOW_FILE.slice(PROJECT_ROOT.length + 1)}`);
}
