// Writes the run-step workflow from steps.json, with its schema built from the block templates.
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { BlockTemplate, StepConfig } from "./generateSteps.ts";
import { getSchemaFromTemplate } from "./templateSchema.ts";

const PROJECT_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const CONFIG_FILE = join(PROJECT_ROOT, "scripts/steps.json");
const WORKFLOW_FILE = join(PROJECT_ROOT, ".claude/workflows/run-step.workflow.js");

// The hook always returns this envelope. Only output changes, so only output is built from the templates.
export function buildWalkResultSchema(config: StepConfig, projectRoot: string): Record<string, unknown> {
    const outputSchemas: Record<string, unknown>[] = [];
    for (const entries of Object.values(config)) {
        for (const entry of entries) {
            const template = JSON.parse(readFileSync(join(projectRoot, entry.template), "utf8")) as BlockTemplate;
            outputSchemas.push(getSchemaFromTemplate(template.output));
        }
    }
    return {
        type: "object",
        properties: {
            ok: { type: "boolean" },
            ran: { type: "array", items: { type: "string" } },
            stoppedAt: { type: "string" },
            why: { type: "string" },
            output: { anyOf: outputSchemas },
        },
        required: ["ok", "ran", "stoppedAt", "why", "output"],
        additionalProperties: false,
    };
}

export function getFirstBox(config: StepConfig): string {
    const firstEntries = Object.values(config)[0] ?? [];
    return firstEntries[0]?.box ?? "";
}

export function buildWorkflowScript(config: StepConfig, projectRoot: string): string {
    const schemaText = JSON.stringify(buildWalkResultSchema(config, projectRoot), null, 4);
    const firstBoxText = JSON.stringify(getFirstBox(config));
    return `// Generated by scripts/generateWorkflow.ts from scripts/steps.json. Do not edit this file.
export const meta = {
    name: 'run-step',
    description: 'Run one diagram block and every block that follows it, through the run-step hook',
    phases: [{ title: 'Run', detail: 'one agent types /run-step and hands back the walk result' }],
}

// Built from every block's output template, so this schema cannot drift from the templates.
const WALK_RESULT_SCHEMA = ${schemaText}

const startBox = args?.box ?? ${firstBoxText}
const startInput = args?.input ?? ''

phase('Run')
const result = await agent(
    \`Type this message exactly, with no other words before or after it: /run-step \${startBox} \${startInput}\`.trim(),
    { label: \`run-step:\${startBox}\`, schema: WALK_RESULT_SCHEMA },
)
log(\`ran \${result.ran.join(' -> ')}, stopped at \${result.stoppedAt} because \${result.why}\`)
return result
`;
}

export function generateWorkflow(configFile: string, workflowFile: string, projectRoot: string): string {
    const config = JSON.parse(readFileSync(configFile, "utf8")) as StepConfig;
    const workflowScript = buildWorkflowScript(config, projectRoot);
    mkdirSync(dirname(workflowFile), { recursive: true });
    writeFileSync(workflowFile, workflowScript);
    return workflowScript;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    generateWorkflow(CONFIG_FILE, WORKFLOW_FILE, PROJECT_ROOT);
    console.log(`wrote ${WORKFLOW_FILE.slice(PROJECT_ROOT.length + 1)}`);
}
